---@class RefmtOptions
---@field default_bindings? boolean
---@field trace? boolean
---@field trailing_comma_filetypes? table<ExprType, string[]>
---@field curly_bracket_filetypes? string[]
---@field shell_filetypes? string[]
---@field multiline_escaped_filetypes? string[]
---@field multiline_deref_unsupported_filetypes? string[]
---@field node_types? table<ExprType,table<string,string[]>>
