prebuilts/build-tools/linux-x86/bin/m4 \
    --fatal-warnings \
    -D mls_num_sens=1 \
    -D mls_num_cats=1024 \
    -D target_arch=arm64 \
    -D target_with_asan=false \
    -D target_with_dexpreopt=true \
    -D target_with_native_coverage=false \
    -D target_build_variant=userdebug \
    -D target_full_treble=true \
    -D target_compatible_property=true \
    -D target_treble_sysprop_neverallow=true \
    -D target_enforce_sysprop_owner=true \
    -D target_exclude_build_test=false \
    -D target_requires_insecure_execmem_for_swiftshader=false \
    -D target_enforce_debugfs_restriction=true \
    -D target_recovery=false \
    -D target_board_api_level=202404 \
    -D target_flag_RELEASE_AVF_ENABLE_DEVICE_ASSIGNMENT=true \
    -D target_flag_RELEASE_AVF_ENABLE_EARLY_VM= \
    -D target_flag_RELEASE_AVF_ENABLE_LLPVM_CHANGES=true \
    -D target_flag_RELEASE_AVF_ENABLE_MICROFUCHSIA= \
    -D target_flag_RELEASE_AVF_ENABLE_NETWORK= \
    -D target_flag_RELEASE_AVF_SUPPORT_CUSTOM_VM_WITH_PARAVIRTUALIZED_DEVICES= \
    -D target_flag_RELEASE_HARDWARE_BLUETOOTH_RANGING_SERVICE=true \
    -D target_flag_RELEASE_RANGING_STACK= \
    -D target_flag_RELEASE_READ_FROM_NEW_STORAGE= \
    -D target_flag_RELEASE_SUPERVISION_SERVICE= \
    -D target_flag_RELEASE_UNLOCKED_STORAGE_API= \
    -s system/sepolicy/flagging/flagging_macros \
    system/sepolicy/private/security_classes \
    system/sepolicy/private/initial_sids \
    system/sepolicy/private/access_vectors \
    system/sepolicy/public/global_macros \
    system/sepolicy/public/neverallow_macros \
    system/sepolicy/private/mls_macros \
    system/sepolicy/private/mls_decl \
    system/sepolicy/private/mls \
    system/sepolicy/private/policy_capabilities \
    system/sepolicy/public/te_macros \
    system/sepolicy/public/ioctl_defines \
    system/sepolicy/public/ioctl_macros \
    system/sepolicy/public/attributes \
    system/sepolicy/public/adbd.te \
    system/sepolicy/public/aidl_lazy_test_server.te \
    system/sepolicy/public/apexd.te \
    system/sepolicy/public/app.te \
    system/sepolicy/public/app_zygote.te \
    system/sepolicy/public/artd.te \
    system/sepolicy/public/asan_extract.te \
    system/sepolicy/public/atrace.te \
    system/sepolicy/public/audioserver.te \
    system/sepolicy/public/blkid.te \
    system/sepolicy/public/blkid_untrusted.te \
    system/sepolicy/public/bluetooth.te \
    system/sepolicy/public/bootanim.te \
    system/sepolicy/public/bootstat.te \
    system/sepolicy/public/bpfloader.te \
    system/sepolicy/public/bufferhubd.te \
    system/sepolicy/public/cameraserver.te \
    system/sepolicy/public/charger.te \
    system/sepolicy/public/charger_vendor.te \
    system/sepolicy/public/crash_dump.te \
    system/sepolicy/public/credstore.te \
    system/sepolicy/public/device.te \
    system/sepolicy/public/dhcp.te \
    system/sepolicy/public/dnsmasq.te \
    system/sepolicy/public/drmserver.te \
    system/sepolicy/public/dumpstate.te \
    system/sepolicy/public/e2fs.te \
    system/sepolicy/public/ephemeral_app.te \
    system/sepolicy/public/evsmanagerd.te \
    system/sepolicy/public/extra_free_kbytes.te \
    system/sepolicy/public/fastbootd.te \
    system/sepolicy/public/file.te \
    system/sepolicy/public/fingerprintd.te \
    system/sepolicy/public/flags_health_check.te \
    system/sepolicy/public/fsck.te \
    system/sepolicy/public/fsck_untrusted.te \
    system/sepolicy/public/gatekeeperd.te \
    system/sepolicy/public/gmscore_app.te \
    system/sepolicy/public/gpuservice.te \
    system/sepolicy/public/hal_graphics_composer.te \
    system/sepolicy/public/healthd.te \
    system/sepolicy/public/heapprofd.te \
    system/sepolicy/public/hwservice.te \
    system/sepolicy/public/hwservicemanager.te \
    system/sepolicy/public/idmap.te \
    system/sepolicy/public/incident.te \
    system/sepolicy/public/incident_helper.te \
    system/sepolicy/public/incidentd.te \
    system/sepolicy/public/init.te \
    system/sepolicy/public/inputflinger.te \
    system/sepolicy/public/installd.te \
    system/sepolicy/public/isolated_app.te \
    system/sepolicy/public/isolated_compute_app.te \
    system/sepolicy/public/kernel.te \
    system/sepolicy/public/keystore.te \
    system/sepolicy/public/keystore_keys.te \
    system/sepolicy/public/llkd.te \
    system/sepolicy/public/lmkd.te \
    system/sepolicy/public/logd.te \
    system/sepolicy/public/logpersist.te \
    system/sepolicy/public/mdnsd.te \
    system/sepolicy/public/mediadrmserver.te \
    system/sepolicy/public/mediaextractor.te \
    system/sepolicy/public/mediametrics.te \
    system/sepolicy/public/mediaprovider.te \
    system/sepolicy/public/mediaserver.te \
    system/sepolicy/public/mediaswcodec.te \
    system/sepolicy/public/mediatranscoding.te \
    system/sepolicy/public/modprobe.te \
    system/sepolicy/public/mtp.te \
    system/sepolicy/public/net.te \
    system/sepolicy/public/netd.te \
    system/sepolicy/public/netutils_wrapper.te \
    system/sepolicy/public/network_stack.te \
    system/sepolicy/public/nfc.te \
    system/sepolicy/public/otapreopt_chroot.te \
    system/sepolicy/public/perfetto.te \
    system/sepolicy/public/performanced.te \
    system/sepolicy/public/platform_app.te \
    system/sepolicy/public/postinstall.te \
    system/sepolicy/public/ppp.te \
    system/sepolicy/public/priv_app.te \
    system/sepolicy/public/prng_seeder.te \
    system/sepolicy/public/profman.te \
    system/sepolicy/public/property.te \
    system/sepolicy/public/radio.te \
    system/sepolicy/public/recovery.te \
    system/sepolicy/public/recovery_persist.te \
    system/sepolicy/public/recovery_refresh.te \
    system/sepolicy/public/rkpd_app.te \
    system/sepolicy/public/rs.te \
    system/sepolicy/public/rss_hwm_reset.te \
    system/sepolicy/public/runas.te \
    system/sepolicy/public/runas_app.te \
    system/sepolicy/public/sdcardd.te \
    system/sepolicy/public/secure_element.te \
    system/sepolicy/public/service.te \
    system/sepolicy/public/servicemanager.te \
    system/sepolicy/public/sgdisk.te \
    system/sepolicy/public/shared_relro.te \
    system/sepolicy/public/shell.te \
    system/sepolicy/public/simpleperf.te \
    system/sepolicy/public/simpleperf_app_runner.te \
    system/sepolicy/public/slideshow.te \
    system/sepolicy/public/statsd.te \
    system/sepolicy/public/su.te \
    system/sepolicy/public/surfaceflinger.te \
    system/sepolicy/public/system_app.te \
    system/sepolicy/public/system_server.te \
    system/sepolicy/public/tee.te \
    system/sepolicy/public/tombstoned.te \
    system/sepolicy/public/toolbox.te \
    system/sepolicy/public/traced.te \
    system/sepolicy/public/traced_perf.te \
    system/sepolicy/public/traced_probes.te \
    system/sepolicy/public/traceur_app.te \
    system/sepolicy/public/ueventd.te \
    system/sepolicy/public/uncrypt.te \
    system/sepolicy/public/untrusted_app.te \
    system/sepolicy/public/update_engine.te \
    system/sepolicy/public/update_verifier.te \
    system/sepolicy/public/usbd.te \
    system/sepolicy/public/vdc.te \
    system/sepolicy/public/vendor_init.te \
    system/sepolicy/public/vendor_misc_writer.te \
    system/sepolicy/public/vendor_modprobe.te \
    system/sepolicy/public/vendor_shell.te \
    system/sepolicy/public/vendor_toolbox.te \
    system/sepolicy/public/virtual_touchpad.te \
    system/sepolicy/public/vndservice.te \
    system/sepolicy/public/vndservicemanager.te \
    system/sepolicy/public/vold.te \
    system/sepolicy/public/vold_prepare_subdirs.te \
    system/sepolicy/public/watchdogd.te \
    system/sepolicy/public/webview_zygote.te \
    system/sepolicy/public/wificond.te \
    system/sepolicy/public/zygote.te \
    system/sepolicy/private/attributes \
    system/sepolicy/private/aconfigd.te \
    system/sepolicy/private/adbd.te \
    system/sepolicy/private/aidl_lazy_test_server.te \
    system/sepolicy/private/apex_test_prepostinstall.te \
    system/sepolicy/private/apexd.te \
    system/sepolicy/private/apexd_derive_classpath.te \
    system/sepolicy/private/app.te \
    system/sepolicy/private/app_neverallows.te \
    system/sepolicy/private/app_zygote.te \
    system/sepolicy/private/art_boot.te \
    system/sepolicy/private/art_exec.te \
    system/sepolicy/private/artd.te \
    system/sepolicy/private/asan_extract.te \
    system/sepolicy/private/atrace.te \
    system/sepolicy/private/audioserver.te \
    system/sepolicy/private/auditctl.te \
    system/sepolicy/private/automotive_display_service.te \
    system/sepolicy/private/binderservicedomain.te \
    system/sepolicy/private/blank_screen.te \
    system/sepolicy/private/blkid.te \
    system/sepolicy/private/blkid_untrusted.te \
    system/sepolicy/private/bluetooth.te \
    system/sepolicy/private/bluetoothdomain.te \
    system/sepolicy/private/bootanim.te \
    system/sepolicy/private/bootstat.te \
    system/sepolicy/private/boringssl_self_test.te \
    system/sepolicy/private/bpfdomain.te \
    system/sepolicy/private/bpfloader.te \
    system/sepolicy/private/bufferhubd.te \
    system/sepolicy/private/camera_service_server.te \
    system/sepolicy/private/cameraserver.te \
    system/sepolicy/private/canhalconfigurator.te \
    system/sepolicy/private/charger.te \
    system/sepolicy/private/charger_type.te \
    system/sepolicy/private/charger_vendor.te \
    system/sepolicy/private/clatd.te \
    system/sepolicy/private/compos_fd_server.te \
    system/sepolicy/private/compos_verify.te \
    system/sepolicy/private/composd.te \
    system/sepolicy/private/coredomain.te \
    system/sepolicy/private/cppreopts.te \
    system/sepolicy/private/crash_dump.te \
    system/sepolicy/private/credstore.te \
    system/sepolicy/private/crosvm.te \
    system/sepolicy/private/custom_vm_setup.te \
    system/sepolicy/private/derive_classpath.te \
    system/sepolicy/private/derive_sdk.te \
    system/sepolicy/private/device_as_webcam.te \
    system/sepolicy/private/dex2oat.te \
    system/sepolicy/private/dexopt_chroot_setup.te \
    system/sepolicy/private/dexoptanalyzer.te \
    system/sepolicy/private/dhcp.te \
    system/sepolicy/private/display_service_server.te \
    system/sepolicy/private/dmesgd.te \
    system/sepolicy/private/dnsmasq.te \
    system/sepolicy/private/domain.te \
    system/sepolicy/private/drmserver.te \
    system/sepolicy/private/dumpstate.te \
    system/sepolicy/private/e2fs.te \
    system/sepolicy/private/early_virtmgr.te \
    system/sepolicy/private/ephemeral_app.te \
    system/sepolicy/private/evsmanagerd.te \
    system/sepolicy/private/extra_free_kbytes.te \
    system/sepolicy/private/fastbootd.te \
    system/sepolicy/private/ferrochrome_app.te \
    system/sepolicy/private/file.te \
    system/sepolicy/private/fingerprintd.te \
    system/sepolicy/private/flags_health_check.te \
    system/sepolicy/private/fsck.te \
    system/sepolicy/private/fsck_untrusted.te \
    system/sepolicy/private/fsverity_init.te \
    system/sepolicy/private/fuseblkd.te \
    system/sepolicy/private/fuseblkd_untrusted.te \
    system/sepolicy/private/fwk_bufferhub.te \
    system/sepolicy/private/gatekeeperd.te \
    system/sepolicy/private/gki_apex_prepostinstall.te \
    system/sepolicy/private/gmscore_app.te \
    system/sepolicy/private/gpuservice.te \
    system/sepolicy/private/gsid.te \
    system/sepolicy/private/hal_allocator.te \
    system/sepolicy/private/hal_allocator_default.te \
    system/sepolicy/private/hal_atrace.te \
    system/sepolicy/private/hal_audio.te \
    system/sepolicy/private/hal_audiocontrol.te \
    system/sepolicy/private/hal_authgraph.te \
    system/sepolicy/private/hal_authsecret.te \
    system/sepolicy/private/hal_bluetooth.te \
    system/sepolicy/private/hal_bootctl.te \
    system/sepolicy/private/hal_broadcastradio.te \
    system/sepolicy/private/hal_camera.te \
    system/sepolicy/private/hal_can.te \
    system/sepolicy/private/hal_cas.te \
    system/sepolicy/private/hal_codec2.te \
    system/sepolicy/private/hal_configstore.te \
    system/sepolicy/private/hal_confirmationui.te \
    system/sepolicy/private/hal_contexthub.te \
    system/sepolicy/private/hal_drm.te \
    system/sepolicy/private/hal_dumpstate.te \
    system/sepolicy/private/hal_evs.te \
    system/sepolicy/private/hal_face.te \
    system/sepolicy/private/hal_fastboot.te \
    system/sepolicy/private/hal_fingerprint.te \
    system/sepolicy/private/hal_gatekeeper.te \
    system/sepolicy/private/hal_gnss.te \
    system/sepolicy/private/hal_graphics_allocator.te \
    system/sepolicy/private/hal_graphics_composer.te \
    system/sepolicy/private/hal_health.te \
    system/sepolicy/private/hal_health_storage.te \
    system/sepolicy/private/hal_identity.te \
    system/sepolicy/private/hal_input_classifier.te \
    system/sepolicy/private/hal_input_processor.te \
    system/sepolicy/private/hal_ir.te \
    system/sepolicy/private/hal_ivn.te \
    system/sepolicy/private/hal_keymaster.te \
    system/sepolicy/private/hal_keymint.te \
    system/sepolicy/private/hal_keymint_system.te \
    system/sepolicy/private/hal_lazy_test.te \
    system/sepolicy/private/hal_light.te \
    system/sepolicy/private/hal_lowpan.te \
    system/sepolicy/private/hal_macsec.te \
    system/sepolicy/private/hal_memtrack.te \
    system/sepolicy/private/hal_neuralnetworks.te \
    system/sepolicy/private/hal_neverallows.te \
    system/sepolicy/private/hal_nfc.te \
    system/sepolicy/private/hal_nlinterceptor.te \
    system/sepolicy/private/hal_oemlock.te \
    system/sepolicy/private/hal_omx.te \
    system/sepolicy/private/hal_power.te \
    system/sepolicy/private/hal_power_stats.te \
    system/sepolicy/private/hal_rebootescrow.te \
    system/sepolicy/private/hal_remoteaccess.te \
    system/sepolicy/private/hal_remotelyprovisionedcomponent_avf.te \
    system/sepolicy/private/hal_secretkeeper.te \
    system/sepolicy/private/hal_secure_element.te \
    system/sepolicy/private/hal_sensors.te \
    system/sepolicy/private/hal_telephony.te \
    system/sepolicy/private/hal_tetheroffload.te \
    system/sepolicy/private/hal_thermal.te \
    system/sepolicy/private/hal_threadnetwork.te \
    system/sepolicy/private/hal_tv_cec.te \
    system/sepolicy/private/hal_tv_hdmi_cec.te \
    system/sepolicy/private/hal_tv_hdmi_connection.te \
    system/sepolicy/private/hal_tv_hdmi_earc.te \
    system/sepolicy/private/hal_tv_input.te \
    system/sepolicy/private/hal_tv_tuner.te \
    system/sepolicy/private/hal_usb.te \
    system/sepolicy/private/hal_usb_gadget.te \
    system/sepolicy/private/hal_uwb.te \
    system/sepolicy/private/hal_vehicle.te \
    system/sepolicy/private/hal_vibrator.te \
    system/sepolicy/private/hal_vr.te \
    system/sepolicy/private/hal_weaver.te \
    system/sepolicy/private/hal_wifi.te \
    system/sepolicy/private/hal_wifi_hostapd.te \
    system/sepolicy/private/hal_wifi_supplicant.te \
    system/sepolicy/private/halclientdomain.te \
    system/sepolicy/private/halserverdomain.te \
    system/sepolicy/private/healthd.te \
    system/sepolicy/private/heapprofd.te \
    system/sepolicy/private/hidl_lazy_test_server.te \
    system/sepolicy/private/hwservice.te \
    system/sepolicy/private/hwservicemanager.te \
    system/sepolicy/private/idmap.te \
    system/sepolicy/private/incident.te \
    system/sepolicy/private/incident_helper.te \
    system/sepolicy/private/incidentd.te \
    system/sepolicy/private/init.te \
    system/sepolicy/private/inputflinger.te \
    system/sepolicy/private/installd.te \
    system/sepolicy/private/isolated_app.te \
    system/sepolicy/private/isolated_app_all.te \
    system/sepolicy/private/isolated_compute_app.te \
    system/sepolicy/private/iw.te \
    system/sepolicy/private/kcmdlinectrl.te \
    system/sepolicy/private/kernel.te \
    system/sepolicy/private/keystore.te \
    system/sepolicy/private/keystore_keys.te \
    system/sepolicy/private/linkerconfig.te \
    system/sepolicy/private/llkd.te \
    system/sepolicy/private/lmkd.te \
    system/sepolicy/private/logd.te \
    system/sepolicy/private/logpersist.te \
    system/sepolicy/private/logviewer_app.te \
    system/sepolicy/private/lpdumpd.te \
    system/sepolicy/private/mdnsd.te \
    system/sepolicy/private/mediadrmserver.te \
    system/sepolicy/private/mediaextractor.te \
    system/sepolicy/private/mediametrics.te \
    system/sepolicy/private/mediaprovider.te \
    system/sepolicy/private/mediaprovider_app.te \
    system/sepolicy/private/mediaserver.te \
    system/sepolicy/private/mediaswcodec.te \
    system/sepolicy/private/mediatranscoding.te \
    system/sepolicy/private/mediatuner.te \
    system/sepolicy/private/microfuchsiad.te \
    system/sepolicy/private/migrate_legacy_obb_data.te \
    system/sepolicy/private/misctrl.te \
    system/sepolicy/private/mlstrustedsubject.te \
    system/sepolicy/private/mm_events.te \
    system/sepolicy/private/modprobe.te \
    system/sepolicy/private/mtectrl.te \
    system/sepolicy/private/net.te \
    system/sepolicy/private/netd.te \
    system/sepolicy/private/netutils_wrapper.te \
    system/sepolicy/private/network_stack.te \
    system/sepolicy/private/nfc.te \
    system/sepolicy/private/odrefresh.te \
    system/sepolicy/private/odsign.te \
    system/sepolicy/private/ot_ctl.te \
    system/sepolicy/private/ot_daemon.te \
    system/sepolicy/private/otapreopt_chroot.te \
    system/sepolicy/private/otapreopt_slot.te \
    system/sepolicy/private/perfetto.te \
    system/sepolicy/private/performanced.te \
    system/sepolicy/private/permissioncontroller_app.te \
    system/sepolicy/private/platform_app.te \
    system/sepolicy/private/postinstall.te \
    system/sepolicy/private/postinstall_dexopt.te \
    system/sepolicy/private/preopt2cachename.te \
    system/sepolicy/private/priv_app.te \
    system/sepolicy/private/prng_seeder.te \
    system/sepolicy/private/profcollectd.te \
    system/sepolicy/private/profman.te \
    system/sepolicy/private/property.te \
    system/sepolicy/private/radio.te \
    system/sepolicy/private/recovery.te \
    system/sepolicy/private/recovery_persist.te \
    system/sepolicy/private/recovery_refresh.te \
    system/sepolicy/private/remote_provisioning_service_server.te \
    system/sepolicy/private/remount.te \
    system/sepolicy/private/rkpd.te \
    system/sepolicy/private/rkpd_app.te \
    system/sepolicy/private/rootdisk_sysdev.te \
    system/sepolicy/private/rs.te \
    system/sepolicy/private/rss_hwm_reset.te \
    system/sepolicy/private/runas.te \
    system/sepolicy/private/runas_app.te \
    system/sepolicy/private/scheduler_service_server.te \
    system/sepolicy/private/sdcardd.te \
    system/sepolicy/private/sdk_sandbox_34.te \
    system/sepolicy/private/sdk_sandbox_all.te \
    system/sepolicy/private/sdk_sandbox_audit.te \
    system/sepolicy/private/sdk_sandbox_current.te \
    system/sepolicy/private/sdk_sandbox_next.te \
    system/sepolicy/private/secure_element.te \
    system/sepolicy/private/sensor_service_server.te \
    system/sepolicy/private/service.te \
    system/sepolicy/private/servicemanager.te \
    system/sepolicy/private/sgdisk.te \
    system/sepolicy/private/shared_relro.te \
    system/sepolicy/private/shell.te \
    system/sepolicy/private/simpleperf.te \
    system/sepolicy/private/simpleperf_app_runner.te \
    system/sepolicy/private/simpleperf_boot.te \
    system/sepolicy/private/slideshow.te \
    system/sepolicy/private/snapshotctl.te \
    system/sepolicy/private/snapuserd.te \
    system/sepolicy/private/stats.te \
    system/sepolicy/private/stats_service_server.te \
    system/sepolicy/private/statsd.te \
    system/sepolicy/private/storaged.te \
    system/sepolicy/private/su.te \
    system/sepolicy/private/surfaceflinger.te \
    system/sepolicy/private/system_app.te \
    system/sepolicy/private/system_server.te \
    system/sepolicy/private/system_suspend.te \
    system/sepolicy/private/system_suspend_internal_server.te \
    system/sepolicy/private/system_suspend_server.te \
    system/sepolicy/private/tee.te \
    system/sepolicy/private/tombstoned.te \
    system/sepolicy/private/toolbox.te \
    system/sepolicy/private/trace_redactor.te \
    system/sepolicy/private/traced.te \
    system/sepolicy/private/traced_perf.te \
    system/sepolicy/private/traced_probes.te \
    system/sepolicy/private/traceur_app.te \
    system/sepolicy/private/ueventd.te \
    system/sepolicy/private/uncrypt.te \
    system/sepolicy/private/untrusted_app.te \
    system/sepolicy/private/untrusted_app_25.te \
    system/sepolicy/private/untrusted_app_27.te \
    system/sepolicy/private/untrusted_app_29.te \
    system/sepolicy/private/untrusted_app_30.te \
    system/sepolicy/private/untrusted_app_32.te \
    system/sepolicy/private/untrusted_app_all.te \
    system/sepolicy/private/update_engine.te \
    system/sepolicy/private/update_engine_common.te \
    system/sepolicy/private/update_verifier.te \
    system/sepolicy/private/updater_app.te \
    system/sepolicy/private/uprobestats.te \
    system/sepolicy/private/usbd.te \
    system/sepolicy/private/userdata_sysdev.te \
    system/sepolicy/private/vdc.te \
    system/sepolicy/private/vehicle_binding_util.te \
    system/sepolicy/private/vendor_init.te \
    system/sepolicy/private/vendor_misc_writer.te \
    system/sepolicy/private/vendor_shell.te \
    system/sepolicy/private/vendor_toolbox.te \
    system/sepolicy/private/vfio_handler.te \
    system/sepolicy/private/virtual_camera.te \
    system/sepolicy/private/virtual_face.te \
    system/sepolicy/private/virtual_fingerprint.te \
    system/sepolicy/private/virtual_touchpad.te \
    system/sepolicy/private/virtualizationmanager.te \
    system/sepolicy/private/virtualizationservice.te \
    system/sepolicy/private/vmlauncher_app.te \
    system/sepolicy/private/vmnic.te \
    system/sepolicy/private/vold.te \
    system/sepolicy/private/vold_prepare_subdirs.te \
    system/sepolicy/private/vzwomatrigger_app.te \
    system/sepolicy/private/wait_for_keymaster.te \
    system/sepolicy/private/watchdogd.te \
    system/sepolicy/private/webview_zygote.te \
    system/sepolicy/private/wificond.te \
    system/sepolicy/private/zygote.te \
    device/generic/goldfish/sepolicy/system_ext/private/platform_app.te \
    system/sepolicy/private/roles_decl \
    system/sepolicy/public/roles \
    system/sepolicy/private/users \
    system/sepolicy/private/initial_sid_contexts \
    system/sepolicy/private/fs_use \
    system/sepolicy/private/genfs_contexts \
    system/sepolicy/private/port_contexts
